# Generated by Django 4.2.2 on 2023-06-23 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dplants', '0002_alter_producto_categoriaid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=50)),
                ('contraseña', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=50)),
            ],
        ),
    ]
