# Generated by Django 4.2.2 on 2023-06-23 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dplants', '0003_usuarios'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuarios',
            new_name='Usuario',
        ),
    ]
