# Generated by Django 4.2.2 on 2023-06-23 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dplants', '0004_rename_usuarios_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoCarrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrePC', models.CharField(max_length=60)),
                ('precioPC', models.IntegerField()),
            ],
        ),
    ]
