# Generated by Django 4.2.2 on 2023-06-26 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dplants', '0009_remove_product_price_product_prices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prices',
            field=models.IntegerField(),
        ),
    ]
