# Generated by Django 4.2.2 on 2023-06-26 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dplants', '0010_alter_product_prices'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
